spring:
  application:
    name: live-betting-app
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # create | create-drop | validate | update

server:
  port: 9070
  tomcat:
    connection-timeout: 2000
  jetty:
    connection-idle-timeout: 2000
  netty:
    connection-timeout: 2000
logging:
  level:
    org.springframework: INFO
    com.ea: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.hibernate.type: TRACE
